### ISSUE TITLE
desktop <-> mobile 오가면 sal-animation 리셋이 안됨.

### ISSUE THREAD

**Issue by jngbng** [bgpworks/boxhero-landing-v2#4]
## 문제 
gatsby-plugin-scroll-reveal 구현이 아마 구현이 observable view에 진입했을 때 sal-animate 를 추가하는데, 이게 @artsy/fresnel 랑 역이면 잘 동작을 안함.

화면을 키우거나 줄이면 dom이 통째로 없어졌다가 생기는데, sal-animate css class가 없는 상태로 생긴다. (dom이 아예 안 보임)
이 때 intersection-observer 에 등록은 안되는 듯?

## 현황

플러그인 사용법은 [여기](https://www.gatsbyjs.com/plugins/gatsby-plugin-scroll-reveal/) 참고.
https://github.com/bgpworks/boxhero-landing-v2/tree/reveal_effect 브랜치에 다시 설정 켜둠.
features 페이지만 시범적으로 적용되어 있음.

## 할 일

desktop layout <-> mobile layout 오갈 때 dom이 아예 안보이는 문제는 없도록 고친다.

레이아웃을 오갈 때는 이전 효과의 진행 상태를 보전할 필요는 없을 듯 하다. 모든 효과가 진행 완료 상태로 생겨도 될 듯. (sal-animated css class 가 추가된 상태)

지금 desktop layout에서는 상단에 메뉴를 누르면 해당 위치까지 smooth scollto 효과로 스스륵 움직이는데,
이 효과를 살리면 부자연스럽게 보일 수 있어서 smooth scrollTo 효과를 다시 지워야 할 수도 있다.

**Comment by BitYoungjae** [comment]
sal의 경우 애니메이션의 상태(재생중인지 등등)가 리액트에 의해 관리되지 않아, desktop-layout mobile-layout으로 상호 변경될 때 기존 상태가 보존도 안되고 초기화도 안되는 문제가 발생한다. 이는 IntersectionObserver를 활용한 상태관리코드를 컴포넌트에 수동으로 붙이거나 관련된 라이브러리(react-intersection-observer)를 사용하는 방법으로 극복이 가능하다.

전자의 경우 하기된 커스텀 훅으로 가볍게 추가가 가능하다.
```js
import { useState, useEffect, useRef } from "react";

export const useIntersectionObserver = (onlyOnce = false, options) => {
  const containerRef = useRef(null);
  const [isIntersecting, setIsIntersecting] = useState(false);

  useEffect(() => {
    if (!(onlyOnce && isIntersecting)) {
      const containerElm = containerRef.current;
      const derivedOptions = {
        root: null,
        rootMargin: "0px",
        threshold: 1.0,
        ...options,
      };

      const observer = new IntersectionObserver((entries) => {
        const [entry] = entries;
        setIsIntersecting(entry.isIntersecting);
      }, derivedOptions);

      containerElm && observer.observe(containerElm);

      return () => containerElm && observer.unobserve(containerElm);
    }
  }, [onlyOnce, options, isIntersecting, setIsIntersecting, containerRef]);

  return { isIntersecting, containerRef };
};
```

후자의 경우 내부적으로 IntersectionObserver 인스턴스를 공유하여 사용(리액트의 Synthetic event와 같이)하는 등 성능상의 이점이 있다는데 얼마나 좋을지는 모르겠다.

다만 IE11 환경에서는 폴리필로 적용이 되는 만큼, 컴포넌트:검증감시기가 1:1이 아닌 n:1로 붙이는게 좋을 것 같긴하다.

**Comment by jngbng** [comment]
sal 아예 제거해버리고 버리자.
